CREATE TABLE `dept` (
  DEPT_ID    BIGINT NOT NULL,
  DEPT_NAME  VARCHAR(20),
  VERSION_NO INTEGER,
  PRIMARY KEY(DEPT_ID)
);

CREATE TABLE `emp` (
  EMP_ID     INTEGER NOT NULL,
  DEPT_ID    INTEGER NOT NULL,
  EMP_NAME   VARCHAR(20),
  HIREDATE   DATE,
  SALARY     NUMERIC(7, 2),
  VERSION_NO INTEGER,
  PRIMARY KEY (EMP_ID)
);

INSERT INTO `dept` VALUES (1, '技術部', 1);
INSERT INTO `dept` VALUES (2, '総務部', 1);

INSERT INTO `emp` VALUES (1, 1, '山田太郎', '1980-12-17', 800, 1);
INSERT INTO `emp` VALUES (2, 2, '山田花子', '1981-02-20', 1600, 1);
