version = "3.11.3"
style = defaultWithAlign
danglingParentheses.preset = true
indentOperator = spray
includeCurlyBraceInSelectChains = true
maxColumn = 120
rewrite.rules = [RedundantParens, ExpandImportSelectors, PreferCurlyFors]
spaces.inImportCurlyBraces = true
binPack.literalArgumentLists = false
indentOperator.topLevelOnly = false
docstrings.style = keep
align.tokens = ["%", "%%"]
runner.dialect = scala212source3
rewrite.scala3.convertToNewSyntax = true
runner.dialectOverride {
  allowSignificantIndentation = false
  allowAsForImportRename = false
  allowStarWildcardImport = false
}
rewrite.imports {
  sort = ascii
  groups = [[".*"]]
}
newlines.topLevelStatementBlankLines = [
  {
    blanks.after = 1
    blanks.before = 1
    maxNest = 0
    regex = "Import|Class|Trait|Object|Enum"
  }
]
